server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edoc
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: Jack5cu$
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

payment.vnPay:
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://10.0.2.2:8080/vnpay/vn-pay-callback
  tmnCode: EDEIUMAF
  secretKey: 8TL0QL450XNEQDQYLLMYL0HMQ339OYUI
  version: 2.1.0
  command: pay
  orderType: topup
#   9704198526191432198
#   NGUYEN VAN A
#	07/15
#   123456
